name: 'Medaillon_dbt_spark'
version: '1.0.0'

profile: 'Medaillon_dbt_spark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  Medaillon_dbt_spark:
    example:
      +materialized: view
    +location_root: "wasbs://silver@datalakegenversion1.blob.core.windows.net/models"
    +create_schema: false
snapshots:
  Medaillon_dbt_spark:
    +target_schema: snapshots
    +location_root: "wasbs://silver@datalakegenversion1.blob.core.windows.net/snapshots"
    create_schema: false